# Generated by Django 3.1.1 on 2020-09-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_School', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
