# Generated by Django 3.1.1 on 2020-09-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Info_School', '0003_auto_20200927_1740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlumnoTota',
            new_name='Alumnoescuela',
        ),
    ]
