# Generated by Django 3.1.1 on 2020-09-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info_School', '0004_auto_20200927_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docenteescuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombeApellido', models.CharField(max_length=20, verbose_name='Apellido y Nombre')),
                ('dni', models.CharField(max_length=10, verbose_name='DNI')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('asignatura', models.CharField(max_length=10, verbose_name='Asignatura:')),
            ],
        ),
    ]
